version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: fleet-postgres
    environment:
      POSTGRES_DB: fleet_db
      POSTGRES_USER: fleet_user
      POSTGRES_PASSWORD: fleet_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  driver-service:
    build: ./DriverSvc
    ports:
      - "8081:8080"
    depends_on:
      - postgres
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/fleet_db
      SPRING_DATASOURCE_USERNAME: fleet_user
      SPRING_DATASOURCE_PASSWORD: fleet_password

  vehicle-service:
    build: ./VehicleSvc
    ports:
      - "8082:8080"
    depends_on:
      - postgres
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/fleet_db
      SPRING_DATASOURCE_USERNAME: fleet_user
      SPRING_DATASOURCE_PASSWORD: fleet_password

  maintenance-service:
    build: ./MaintenanceSvc
    ports:
      - "8083:8080"
    depends_on:
      - postgres
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/fleet_db
      SPRING_DATASOURCE_USERNAME: fleet_user
      SPRING_DATASOURCE_PASSWORD: fleet_password

  ai-agent-service:
    build: ./AIAgentSvc
    ports:
      - "8084:8080"
    depends_on:
      - postgres
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/fleet_db
      SPRING_DATASOURCE_USERNAME: fleet_user
      SPRING_DATASOURCE_PASSWORD: fleet_password

volumes:
  postgres_data: 